---

- name: Get Nginx apt key
  apt_key:
    url: '{{ nginx_repo_key_url }}'

- name: Configure Nginx official repository (stable)
  apt_repository:
    repo: 'deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx'
    filename: nginx

- name: Install Nginx
  apt:
    name: nginx

- name: Remove default configuration
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: reload nginx

- name: Create nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: Setup logrotate
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/nginx

- name: Create vhosts configuration directory
  file:
    path: /etc/nginx/vhosts
    state: directory

- name: Add default vhost
  copy:
    src: default_vhost.conf
    dest: /etc/nginx/vhosts/default.conf
  when: nginx_default_vhost_enabled
  notify: reload nginx

- name: Add status vhost
  copy:
    src: status_vhost.conf
    dest: /etc/nginx/vhosts/status.conf
  when: nginx_status_vhost_enabled
  notify: reload nginx

- name: Enable and start Nginx systemd unit
  systemd:
    name: nginx.service
    enabled: true
    state: started
